name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dev packages
        run: |
          sudo apt-get install -y build-essential

      - name: Compile the code
        run: |
          ./configure
          make

      - name: Run the unit tests
        run: |
          make test
